{% set version = "1.0.0b19" %}

package:
  name: emperor
  version: {{ version }}

source:
  fn: emperor-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/e/emperor/emperor-{{ version }}.tar.gz
  sha256: c3523649c3fe9f7f57745bda8e5f3673aa9e98530c136b0edc9113402ca0ff0c

build:
  number: 0
  skip: true  # [win]
  script: python setup.py install --record=record.txt

requirements:
  build:
    - python
    - scipy >=0.17.0
    - future
    - jinja2
    - scikit-bio >=0.4.1,<0.5.0  # [py2k]
    - scikit-bio >=0.4.1  # [py3k]
    - numpy >=1.7
    - pandas
    - click
    - setuptools

  run:
    - python
    - scipy >=0.17.0
    - future
    - jinja2
    - scikit-bio >=0.4.1,<0.5.0  # [py2k]
    - scikit-bio >=0.4.1  # [py3k]
    - numpy >=1.7
    - pandas
    - click
    - setuptools

test:
  requires:
    - pep8
    - flake8
    - nose
  imports:
    - emperor
    - emperor.qiime_backports

about:
  home: http://emperor.microbio.me
  license: BSD 3-Clause
  summary: 'Emperor a tool for the analysis and visualization of large microbial ecology datasets'

extra:
    recipe-maintainers:
        - ElDeveloper
