{% set version = "1.0.0beta7" %}

package:
  name: emperor
  version: {{ version }}

source:
  fn: emperor-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/e/emperor/emperor-{{ version }}.tar.gz
  md5: ef1dc6d0d26f6e8cde4a73b283b5677a

build:
  number: 2
  skip: true  # [win]
  script: python setup.py install --record=record.txt

requirements:
  build:
    - python
    - scipy >=0.17.0
    - future
    - jinja2
    - scikit-bio >=0.4.1,<0.5.0  # [py2k]
    - scikit-bio >=0.4.1  # [py3k]
    - numpy >=1.7
    - pandas
    - click

  run:
    - python
    - scipy >=0.17.0
    - future
    - jinja2
    - scikit-bio >=0.4.1,<0.5.0  # [py2k]
    - scikit-bio >=0.4.1  # [py3k]
    - numpy >=1.7
    - pandas
    - click

test:
  imports:
    - emperor
    - emperor.qiime_backports

about:
  home: http://emperor.microbio.me
  license: BSD 3-Clause
  summary: 'Emperor a tool for the analysis and visualization of large microbial ecology datasets'

extra:
    recipe-maintainers:
        - ElDeveloper
