travis:
  secure:
    BINSTAR_TOKEN: b+pjkE7ArwwJ3+AzGMe/+aEmkwqcqh/3Yx51zHt+6bScps/aCDJO093QsAYDbeQvG6rGCdO8XS8P4gNxbt1gzKVJjFhE+QQ29E+48nSSfXMUCwPdpmtbWLXfGRDguv+K4SJEEjxJBJG9JlIR8AD1vEfleK+7LGUpf+kbU20IAM0ik6m2M2D1+4mVxstu5Lcf695jplVJeL5HVOvPLw2hxOr9QMExHJ8/diumAWmooDMiQAqmZLSB99EUxlhz9eQDqzfT0ku9fmb+NV0Q1WcjyR03/wfgB723Zs/OM6SVEocYL1pBus1WET1uJkqDhxFJ6COVPEP1eDSsTBQNt1BekqyBQY+rSWCg7GoZ7F6+hiNtA4X9SlDP1gvNdMgeI2JJfcPUfR79eB5UZRrmKEjb7sdOQzjKEsYkB6JX6d/GIl8tf0bInek4bZlEj4GfjGfkmhJ97QeAIAoGh59+Ostxh3fxGRiuW5wMjd7UKg/FXkD7/vs4f7xLkgYNh3NLD3OSRuuel/7gC6rtxPTfpsWsU5ZB1affyqeqZbply4jQ1zN3cISMIRRwX5oKaRwuBBBb4gEyIxEYahfw86O44Jaej76cxyPALITEnrBeKMBc48fMxLbXBilqBR3KkGNkDaJ1SjEcsl6xhxlJDTZP6XCMD4vXpKuvQC/Ns2BsjTYN4YE=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
