travis:
  secure:
    BINSTAR_TOKEN: S7Ii7mfNJxTd3lxnVrT6qTPa+WW45dALNZ9D6xA0J6DZ+FIpTmNLMJAJknfw3TFdq9e2chsLnH9eMQ3UkwiLiuVM1Z+l0k4sVj0IPmzTkof6jUhjKujmn+oqUOQvRXtw3FDukTxUQGKS/iQginffMYCJGQuXo4r12AdA4fNm/XgYJ8XhYMHmosHImemOMv2N5qDLlqz7pIjlIYQ6fWS+04squKpSaYvbk32JrgGryJ8PRHjOBJQCx1s3kAUMNePDu7vvSPyyOlC3T5TecfPeJ9WGzPzyN6LMWeFZ6U0boj4sQ6MveRJtWe6sdL4oNIit0LYMY83Y3kDGC5uF/n/BiKu3SkyLktR3D/0ExayaRN6hdrBH8Il0jUnK3qZLvJSow0lMhcQr+kS5NGvXgceDLU1epU0k+cnzjtkpW+0RHid0snEmu54YBdyxZc7hMEIn8cq+aKYuJwcPv4UKR73SFuHLFi6fPeUZKW2/qY8bqzaZskuweeGpvv95fXyhLP99ScP4sCHEvL3WqStkCualY6sDHfBF/WkHv0AWgwY5TFXVTyTO9xzye5my4D7ySybz/IRM1ebYMvdOxJlM1V6+CsOQ6cf0I/FPEHY4gVQQe3twZTTs4pWyWlh3vWszI6R1mOlgIHcGVbZLNs5X+XFH0zGzlIoR6Pkm5pL3rqr/88Q=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
